sudo: false
language: java
script: ./reset-apply-build.sh
jdk:
  - oraclejdk8
notifications:
  email: false
cache:
  directories:
    - $HOME/.m2
    - BungeeCord
before-cache:
  - rm -rf $HOME/.m2/repository/me/minotopia/flexpipe