sudo: false
language: java
script:
  - ./reset-apply-build.sh
  - rm -rfv target
  - rm -rfv BungeeCord/**/target
  - rm -rfv $HOME/.m2/repository/me/minotopia/flexpipe
jdk:
  - oraclejdk8
notifications:
  email: false
cache:
  directories:
    - $HOME/.m2
    - BungeeCord
