sudo: false
language: java
script:
  - ./reset-apply-build.sh
  - rm -rf BungeeCord/**/target/
  - rm -rf $HOME/.m2/repository/me/minotopia/flexpipe
jdk:
  - oraclejdk8
notifications:
  email: false
cache:
  directories:
    - $HOME/.m2
    - BungeeCord
